# DSCI235 Spring 2026 Final Project
### Team Members: Ayden Garza, Natalie Houk

### Project Overview
For this project, we will be analyzing the [Stack Overflow Annual Developer Survey (2024)](https://www.kaggle.com/datasets/berkayalan/stack-overflow-annual-developer-survey-2024/) results. These data were accessed April 2026. Natalie and I chose to analyze this dataset because it provides insight into the trends and changes that are taking place in the world of software developement. We are both interested in this industry, and during this time of AI, we think it's important to understand where the industry is headed, and analyzing this dataset can help us do that.

 Now having said that, let's load the data!

In [89]:
import pandas
from pathlib import Path

TESTING = True 

results_path = "survey_results_public.csv"

df = None
if Path(results_path).exists():
    df = pandas.read_csv(results_path)
else:
    print("Downloading data from Kaggle..")
    import kagglehub
    from kagglehub import KaggleDatasetAdapter
    df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS, "berkayalan/stack-overflow-annual-developer-survey-2024", results_path)
    df.to_csv(results_path, index=False)

if TESTING:
    local_df = pandas.read_csv(results_path)
    kaggle_df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS, "berkayalan/stack-overflow-annual-developer-survey-2024", results_path)
    assert local_df.equals(kaggle_df)
    print("TESTING PASSES")

df

/var/folders/hk/k0xs70jx4ml1xd6j48j6rgq80000gn/T/ipykernel_8657/3362158543.py:20: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  kaggle_df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS, "berkayalan/stack-overflow-annual-developer-survey-2024", results_path)

TESTING PASSES

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65432,65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65433,65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65436,65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Now we need to get the schema of the dataset to understand what each column is, whether the column was required in the survey, and the type of data the column is.

In [90]:
TESTING = True 

schema_path = "survey_results_schema.csv"

schema_df = None
if Path(schema_path).exists():
    schema_df = pandas.read_csv(schema_path)
else:
    print("Downloading data from Kaggle..")
    import kagglehub
    from kagglehub import KaggleDatasetAdapter
    schema_df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS, "berkayalan/stack-overflow-annual-developer-survey-2024", schema_path)
    schema_df.to_csv(schema_path, index=False)

if TESTING:
    local_schema_df = pandas.read_csv(schema_path)
    kaggle_schema_df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS, "berkayalan/stack-overflow-annual-developer-survey-2024", schema_path)
    assert local_schema_df.equals(kaggle_schema_df)
    print("TESTING PASSES")

schema_df

/var/folders/hk/k0xs70jx4ml1xd6j48j6rgq80000gn/T/ipykernel_8657/2376057685.py:17: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  kaggle_schema_df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS, "berkayalan/stack-overflow-annual-developer-survey-2024", schema_path)

TESTING PASSES

,qid,qname,question,force_resp,type,selector
0,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
1,QID127,Age,What is your age?*,True,MC,SAVR
2,QID296,Employment,Which of the following best describes your cur...,True,MC,MAVR
3,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
4,QID341,Check,Just checking to make sure you are paying atte...,True,MC,SAVR
...,...,...,...,...,...,...
82,QID337,JobSatPoints_7,"Learning and using new technology, including p...",NaN,MC,MAVR
83,QID337,JobSatPoints_8,"Designing and building environments, databases...",NaN,MC,MAVR
84,QID337,JobSatPoints_9,"Being a power user of a tool, developer langua...",NaN,MC,MAVR
85,QID337,JobSatPoints_10,Working with new and/or top-quality hardware,NaN,MC,MAVR
86,QID337,JobSatPoints_11,A well-staffed/sourced internal network that m...,NaN,MC,MAVR

### Wrangling The Data
Now that we have our data loaded, we have to wrangle it. There is a lot of information here, we don't need all of it. Let's first start with seeing what the column situation looks like.

In [91]:
for c in df.columns: print(c) #using this so we can expand and view as scrollable element
print(df.shape)

ResponseId
MainBranch
Age
Employment
RemoteWork
Check
CodingActivities
EdLevel
LearnCode
LearnCodeOnline
TechDoc
YearsCode
YearsCodePro
DevType
OrgSize
PurchaseInfluence
BuyNewTool
BuildvsBuy
TechEndorse
Country
Currency
CompTotal
LanguageHaveWorkedWith
LanguageWantToWorkWith
LanguageAdmired
DatabaseHaveWorkedWith
DatabaseWantToWorkWith
DatabaseAdmired
PlatformHaveWorkedWith
PlatformWantToWorkWith
PlatformAdmired
WebframeHaveWorkedWith
WebframeWantToWorkWith
WebframeAdmired
EmbeddedHaveWorkedWith
EmbeddedWantToWorkWith
EmbeddedAdmired
MiscTechHaveWorkedWith
MiscTechWantToWorkWith
MiscTechAdmired
ToolsTechHaveWorkedWith
ToolsTechWantToWorkWith
ToolsTechAdmired
NEWCollabToolsHaveWorkedWith
NEWCollabToolsWantToWorkWith
NEWCollabToolsAdmired
OpSysPersonal use
OpSysProfessional use
OfficeStackAsyncHaveWorkedWith
OfficeStackAsyncWantToWorkWith
OfficeStackAsyncAdmired
OfficeStackSyncHaveWorkedWith
OfficeStackSyncWantToWorkWith
OfficeStackSyncAdmired
AISearchDevHaveWorkedWith
AISearchDevWantToWorkWith
AISearchDevAdmired
NEWSOSites
SOVisitFreq
SOAccount
SOPartFreq
SOHow
SOComm
AISelect
AISent
AIBen
AIAcc
AIComplex
AIToolCurrently Using
AIToolInterested in Using
AIToolNot interested in Using
AINextMuch more integrated
AINextNo change
AINextMore integrated
AINextLess integrated
AINextMuch less integrated
AIThreat
AIEthics
AIChallenges
TBranch
ICorPM
WorkExp
Knowledge_1
Knowledge_2
Knowledge_3
Knowledge_4
Knowledge_5
Knowledge_6
Knowledge_7
Knowledge_8
Knowledge_9
Frequency_1
Frequency_2
Frequency_3
TimeSearching
TimeAnswering
Frustration
ProfessionalTech
ProfessionalCloud
ProfessionalQuestion
Industry
JobSatPoints_1
JobSatPoints_4
JobSatPoints_5
JobSatPoints_6
JobSatPoints_7
JobSatPoints_8
JobSatPoints_9
JobSatPoints_10
JobSatPoints_11
SurveyLength
SurveyEase
ConvertedCompYearly
JobSat
(65437, 114)

114 columns is too much data to be working with for our intents and purposes, so we are going to drop some of the columns that won't aid in our analysis. We are going to make use of the `survey_results_schema.csv` file that is part of the dataset on Kaggle that describes what the more obscure columns are.

Looking at the schema, we quickly can see that the "knowledge" columns won't be of use for us in this analysis. These columns are talking about work-place specific resources and procedures. We can drop these.

There are many more columns in here that aren't going to be useful, so we are going to loop through each column and drop them accordingly.

In [95]:
for c in df.columns:
    if "Knowledge" in c or "JobSat" in c or "Frequency" in c or "OfficeStack" in c or "Professional" in c:
        df = df.drop(c, axis=1)

print("Num columns after drop:", df.shape[1])
for c in df.columns: print(c)

Num columns after drop: 82
ResponseId
MainBranch
Age
Employment
RemoteWork
Check
CodingActivities
EdLevel
LearnCode
LearnCodeOnline
TechDoc
YearsCode
YearsCodePro
DevType
OrgSize
PurchaseInfluence
BuyNewTool
BuildvsBuy
TechEndorse
Country
Currency
CompTotal
LanguageHaveWorkedWith
LanguageWantToWorkWith
LanguageAdmired
DatabaseHaveWorkedWith
DatabaseWantToWorkWith
DatabaseAdmired
PlatformHaveWorkedWith
PlatformWantToWorkWith
PlatformAdmired
WebframeHaveWorkedWith
WebframeWantToWorkWith
WebframeAdmired
EmbeddedHaveWorkedWith
EmbeddedWantToWorkWith
EmbeddedAdmired
MiscTechHaveWorkedWith
MiscTechWantToWorkWith
MiscTechAdmired
ToolsTechHaveWorkedWith
ToolsTechWantToWorkWith
ToolsTechAdmired
NEWCollabToolsHaveWorkedWith
NEWCollabToolsWantToWorkWith
NEWCollabToolsAdmired
OpSysPersonal use
AISearchDevHaveWorkedWith
AISearchDevWantToWorkWith
AISearchDevAdmired
NEWSOSites
SOVisitFreq
SOAccount
SOPartFreq
SOHow
SOComm
AISelect
AISent
AIBen
AIAcc
AIComplex
AIToolCurrently Using
AIToolInterested in Using
AIToolNot interested in Using
AINextMuch more integrated
AINextNo change
AINextMore integrated
AINextLess integrated
AINextMuch less integrated
AIThreat
AIEthics
AIChallenges
TBranch
ICorPM
WorkExp
TimeSearching
TimeAnswering
Frustration
Industry
SurveyLength
SurveyEase
ConvertedCompYearly

We have dropped around 30 columns, and the columns that currently exist give rise to some interesting questions! But before we get started with that, we are going to limit our analysis to *professional developers only* to gain insight into what the landscape of the professional software development industry looks like.

In [96]:
df = df[df['Employment'].str.contains("Employed")]
df.shape

(48801, 82)

We lost about 20,000 respondants from that. Sorry students and hobbyists ;-; . Now, let's move on to answering some interesting questions. Looking at the columns, there are a few columns that give insight into which platforms/languages/technologies are most admired, most worked with, and most sought after. So, we want to find out in each category what language/platform/technology was *MOST* sought after, most used, and most admired in 2024.

In [97]:
df

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,TBranch,ICorPM,WorkExp,TimeSearching,TimeAnswering,Frustration,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,Yes,Individual contributor,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,No,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
6,7,"I am not primarily a developer, but I write co...",35-44 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Written...,...,No,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
8,9,I code primarily as a hobby,45-54 years old,"Employed, full-time",In-person,Apples,Hobby,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Other online resources ...,Stack Overflow;Written-based Online Courses,...,No,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65431,65432,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,Yes,Individual contributor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65432,65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65433,65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,Yes,Individual contributor,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for subject in ["Platform", "Language", "Webframe"]:
    admired_col = subject + "Admired"
    worked_with_col = subject + "HaveWorkedWith"
    desired_col = subject + "WantToWorkWith"
    cols_to_keep = [admired_col, worked_with_col, desired_col]
    curr_df = df[cols_to_keep]

    admired_count_groups = curr_df.groupby(admired_col).count()
    admired_count_groups = admired_count_groups.drop(admired_count_groups.columns[0], axis=1)
    most_admired = admired_count_groups.idxmax().iloc[0]

    worked_with_count_groups = curr_df.groupby(worked_with_col).count()
    worked_with_count_groups = worked_with_count_groups.drop(worked_with_count_groups.columns[0], axis=1)
    most_worked_with = worked_with_count_groups.idxmax().iloc[0]

    desired_count_groups = curr_df.groupby(desired_col).count()
    desired_count_groups = desired_count_groups.drop(desired_count_groups.columns[0], axis=1)
    most_desired = desired_count_groups.idxmax().iloc[0]

    print(f"Most desired {subject}: {most_desired}")
    print(f"Most admired {subject}: {most_admired}")
    print(f"Most worked with {subject}: {most_worked_with}")

Most desired Platform: Amazon Web Services (AWS)
Most admired Platform: Amazon Web Services (AWS)
Most worked with Platform: Amazon Web Services (AWS)
Most desired Language: Python
Most admired Language: Python
Most worked with Language: HTML/CSS;JavaScript;TypeScript
Most desired Webframe: React
Most admired Webframe: React
Most worked with Webframe: Spring Boot